# Generated by Django 4.1 on 2022-08-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_art_photo_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(max_length=1000),
        ),
    ]
