# Generated by Django 4.1 on 2022-08-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_art_options_art_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='art',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='picture',
        ),
        migrations.AddField(
            model_name='artist',
            name='contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.art')),
            ],
        ),
    ]
