# Generated by Django 4.1 on 2022-08-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_art_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
