# Generated by Django 4.1 on 2022-08-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_art_artist_delete_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={},
        ),
        migrations.RemoveField(
            model_name='art',
            name='date',
        ),
    ]
